### ISSUE TITLE
Adapt VirMet Run Analysis to work with new VirMet orgs_species_found.tsv file

### ISSUE THREAD

**Issue by sschmutz** [medvir/shiny-server#5]
During the last VirMet update, the layout of the `orgs_species_found.tsv` file changed a bit. It now contains additional infos which somehow fails the current shiny app.

We could now
a) fix it so it'll accept both old and new `orgs_species_found.tsv` files
b) look forward and change it so it's optimized for the new output

**Comment by mihuber** [comment]
- make window for selecting samples bigger
- include fungal and bovine reads in taxonomic overview

**Comment by sschmutz** [comment]
All issues closed in a series of commits
